### PR TITLE
Update 0001-wined3d-Implement-updating-swap-interval-through-win.patch

### PR DESCRIPTION
**Pull request by omega13a**
Allows the patch file to be applied

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
not compiling:
../../../wine-git/dlls/dxgi/swapchain.c: In function ‘dxgi_swapchain_Present’:
../../../wine-git/dlls/dxgi/swapchain.c:186:44: error: ‘This’ undeclared (first use in this function)
     HRESULT hr = wined3d_swapchain_present(This->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
                                            ^~~~
../../../wine-git/dlls/dxgi/swapchain.c:186:44: note: each undeclared identifier is reported only once for each function it appears in
../../../wine-git/dlls/dxgi/swapchain.c:186:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     HRESULT hr = wined3d_swapchain_present(This->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
     ^~~~~~~
../../../wine-git/dlls/dxgi/swapchain.c:186:13: warning: unused variable ‘hr’ [-Wunused-variable]
     HRESULT hr = wined3d_swapchain_present(This->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
             ^~
../../../wine-git/dlls/dxgi/swapchain.c: In function ‘dxgi_swapchain_Present1’:
../../../wine-git/dlls/dxgi/swapchain.c:565:10: error: too few arguments to function ‘wined3d_swapchain_present’
     hr = wined3d_swapchain_present(swapchain->wined3d_swapchain, NULL, NULL, NULL, 0);
          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../wine-git/dlls/dxgi/dxgi_private.h:39:0,
                 from ../../../wine-git/dlls/dxgi/swapchain.c:23:
../../../wine-git/include/wine/wined3d.h:2673:17: note: declared here
 HRESULT __cdecl wined3d_swapchain_present(struct wined3d_swapchain *swapchain,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/gloriouseggroll/Development/wine-staging-git/src/wine-staging-git-64-build/dlls/fontsub'
gcc -m64 -c -o mesh.o ../../../wine-git/dlls/glu32/mesh.c -I. -I../../../wine-git/dlls/glu32 \
  -I../../include -I../../../wine-git/include -D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
gcc -m64 -c -o icm.o ../../../../wine-git/dlls/gdi32/tests/icm.c -I. \
  -I../../../../wine-git/dlls/gdi32/tests -I../../../include -I../../../../wine-git/include \
  -D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement \
  -Wempty-body -Wignored-qualifiers -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -D_FORTIFY_SOURCE=2 \
  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
make[1]: *** [Makefile:479: swapchain.o] Error 1

**Comment by JackoboLeChocobo** [comment]
I use this after application of the patch to correct the issue : Need to confirm if the modifications are OK.

--- a/dlls/dxgi/factory.c
+++ b/dlls/dxgi/factory.c
@@ -174,7 +174,7 @@
 static HRESULT STDMETHODCALLTYPE dxgi_factory_MakeWindowAssociation(IWineDXGIFactory *iface,
         HWND window, UINT flags)
 {
-    struct dxgi_factory *factory = impl_from_IDXGIFactory1(iface);
+    struct dxgi_factory *factory = impl_from_IWineDXGIFactory(iface);
 
     FIXME("iface %p, window %p, flags %#x stub!\n", iface, window, flags);
 
@@ -188,7 +188,7 @@
 
 static HRESULT STDMETHODCALLTYPE dxgi_factory_GetWindowAssociation(IWineDXGIFactory *iface, HWND *window)
 {
-    struct dxgi_factory *factory = impl_from_IDXGIFactory1(iface);
+    struct dxgi_factory *factory = impl_from_IWineDXGIFactory(iface);
 
     FIXME("iface %p, window %p stub!\n", iface, window);
 
--- a/dlls/dxgi/swapchain.c
+++ b/dlls/dxgi/swapchain.c
@@ -183,7 +183,7 @@
             FIXME("Unimplemented sync interval %u.\n", sync_interval);
     }
     
-    HRESULT hr = wined3d_swapchain_present(This->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
+    HRESULT hr = wined3d_swapchain_present(swapchain->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
 
     return IDXGISwapChain1_Present1(&swapchain->IDXGISwapChain1_iface, sync_interval, flags, NULL);
 }
@@ -544,7 +544,8 @@
 {
     struct dxgi_swapchain *swapchain = impl_from_IDXGISwapChain1(iface);
     HRESULT hr;
-
+	DWORD swap_interval = 0;
+	
     TRACE("iface %p, sync_interval %u, flags %#x, present_parameters %p.\n",
             iface, sync_interval, flags, present_parameters);
 
@@ -556,13 +557,24 @@
         return S_OK;
     }
 
-    if (sync_interval)
-        FIXME("Unimplemented sync interval %u.\n", sync_interval);
+    switch (sync_interval)
+    {
+        case 0:
+            swap_interval = WINED3DPRESENT_INTERVAL_IMMEDIATE;
+            break;
+        case 1:
+            swap_interval = WINED3DPRESENT_INTERVAL_ONE;
+            break;
+        default:
+            FIXME("Unimplemented sync interval %u.\n", sync_interval);
+    }
+
     if (present_parameters)
         FIXME("Ignored present parameters %p.\n", present_parameters);
 
     wined3d_mutex_lock();
-    hr = wined3d_swapchain_present(swapchain->wined3d_swapchain, NULL, NULL, NULL, 0);
+    
+    hr = wined3d_swapchain_present(swapchain->wined3d_swapchain, NULL, NULL, NULL, swap_interval, 0);
     wined3d_mutex_unlock();
 
     return hr;

**Comment by GloriousEggroll** [comment]
@JackoboLeChocobo Tried to check the patch but the url gives me 404 error

**Comment by obsequiousnewt** [comment]
Closing since this was fixed by cf19a5d6d636bbf8d46603aad88f29d7b627a8c6.

**Pull request closed without merging**
