### PR TITLE
add wined3d-setpixelformat to fix #18490

### PR DESCRIPTION
**Pull request by stefson**
This is a fix for Total War: Empire and Total War: Napoleon; without the patch the game crashes when switching from Campaign mode to Battle mode. Please tell me if you want to accept the patch, so that I can test it with the full staging patchset for conflicts.

### CODE REVIEW

**Comment by zfigura** [comment]
This should already be fixed by d3d9-Desktop_Window; why is this not enough?

**Comment by stefson** [comment]
Last I tested was 3.13 where it didn't work, but now with 3.15 it does. I'm going to test wine-vanilla with the d3d9-Desktop_Window patch to see if that's a propper replacement.

**Comment by stefson** [comment]
ok, it works with the staging patchset and >=wine-3.15 

May I ask, why does upstream not add it to the tree?

**Comment by zfigura** [comment]
The comments attached to the patch state that it's incorrect, and as such it can't be applied directly upstream.

Closing since this patchset is unnecessary.

**Pull request closed without merging**
