### PR TITLE
Update 0001-ws2_32-Proper-WSACleanup-implementation-using-winese.patch

### PR DESCRIPTION
**Pull request by omega13a**
Allows the patch file to be applied.

Note: after I made the changes to this one, all the patches were applied successfully. Don't know if things will compile though... Checking now.

### CODE REVIEW

**Comment by omega13a** [comment]
There's a mistake somewhere in all the proposed changes I made. Attached is what happens when I tried to build an RPM. If it helps, I've also attached the spec file.
[wine_fails.txt](https://github.com/wine-staging/wine-staging/files/1735496/wine_fails.txt)
[wine.spec.txt](https://github.com/wine-staging/wine-staging/files/1735502/wine.spec.txt)

**Comment by GloriousEggroll** [comment]
In your logL

**device.c: In function 'd3d10_device_GenerateMips':**
device.c:7554:38: error: 'view' redeclared as different kind of symbol
     struct d3d_shader_resource_view *view = unsafe_impl_from_ID3D10ShaderResourceView(shader_resource_view);
                                      ^~~~
device.c:7551:35: note: previous definition of 'view' was here
         ID3D10ShaderResourceView *view)
                                   ^~~~
device.c:7554:87: error: 'shader_resource_view' undeclared (first use in this function)
     struct d3d_shader_resource_view *view = unsafe_impl_from_ID3D10ShaderResourceView(shader_resource_view);
                                                                                       ^~~~~~~~~~~~~~~~~~~~
device.c:7554:87: note: each undeclared identifier is reported only once for each function it appears in
Makefile:286: recipe for target 'device.o' failed
make[1]: *** [device.o] Error 1
make[1]: *** Waiting for unfinished jobs...

try disabling the GenerateMipmaps patchset and see if it errors still.

**Comment by omega13a** [comment]
Do you mean the wined3d-GenerateMips patch set?

**Comment by GloriousEggroll** [comment]
yes sorry, i have a list of patches to correct but didnt have it in front of me. Here's the list of patchsets I currently have disabled in order for it to compile.

https://github.com/GloriousEggroll/wine-staging/blob/testing/TODO.md

**Comment by omega13a** [comment]
Here's the result for disabling wined3d-GenerateMips patch set and everything that depends on it:
[wine_fails2.txt](https://github.com/wine-staging/wine-staging/files/1735750/wine_fails2.txt)

**Comment by GloriousEggroll** [comment]
ERROR: Patchset **wined3d-CSMT_Helper disabled, but wined3d-CSMT_Main depends on that**.

youll have to disable both of those. here's what I'm currently using, I remove them from the list if im testing them and leave the rest disabled, then fix them one by one:

-W wined3d-dxgi_swapchain_Present -W ws2_32-WSACleanup -W bcrypt-Improvements -W crypt32-ECDSA_Cert_Chains -W dxgi-MakeWindowAssociation -W inseng-Implementation -W ntdll-LdrRegisterDllNotification -W ntdll-HashLinks -W shell32-UnixFS -W wined3d-1DTextures -W d3d11-ID3D11Texture1D -W d3d11-Deferred_Context -W wined3d-Revert_Surface_Blt -W windowscodecs-TIFF_Support -W windowscodecs-32bppPRGBA -W wined3d-CSMT_Helper -W wined3d-CSMT_Main -W ntdll-CLI_Images -W wined3d-DXTn -W d3dx9_36-DXTn -W wined3d-GenerateMips -W wined3d-Dual_Source_Blending

check the todo list link i gave, its organized so that patch sets that depend on others are on the same line in the list. example from the list:

-W wined3d-GenerateMips  
-W wined3d-1DTextures -W d3d11-ID3D11Texture1D -W d3d11-Deferred_Context -W wined3d-CSMT_Helper -W wined3d-CSMT_Main  

in the second line, the first patchset wined3d-1DTextures has a compile problem, and every patch set in that line after it depends on it.

**Comment by JackoboLeChocobo** [comment]
The solution to correct the issue after application of the patch : Need confirmation

https://gitlab.com/JackoboLeChocobo/WineScripts/blob/master/wine-staging-3.2/patches-after-staging-app/after-staging-app-ws2_32.patch

**Comment by GloriousEggroll** [comment]
@JackoboLeChocobo both links give me a 404 error

**Comment by GloriousEggroll** [comment]
fixed 669b58c813ff750917c4cbd2bd788eb9340f7688

**Pull request closed without merging**
