### PR TITLE
Update 0002-wined3d-Implement-hardware-indexed-vertex-blending-w.patch

### PR DESCRIPTION
**Pull request by omega13a**
Allows the patch file to be applied

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
this applies but does not compile after adding the subsequent patches:

In file included from ../../../../wine-git/dlls/d3d9/tests/visual.c:34:0:
../../../../wine-git/dlls/d3d9/tests/visual.c: In function ‘do_test_indexed_vertex_blending’:
../../../../wine-git/dlls/d3d9/tests/visual.c:20377:65: error: ‘identity’ undeclared (first use in this function); did you mean ‘WidenPath’?
     hr = IDirect3DDevice9_SetTransform(device, D3DTS_TEXTURE0, &identity);

**Comment by omega13a** [comment]
That's odd. All 0002-wined3d-Implement-hardware-indexed-vertex-blending-w.patch does to dlls/d3d9/tests/visual.c is change 
`todo_wine win_skip("(%s) Too few vertex blend matrices supported: MaxVertexBlendMatrices=%u, MaxVertexBlendMatrixIndex=%u.\n",`
to
`win_skip("(%s) Too few vertex blend matrices supported: MaxVertexBlendMatrices=%u, MaxVertexBlendMatrixIndex=%u.\n",`

**Comment by JackoboLeChocobo** [comment]
I use this after application of the patch to correct the issue : Someone can confirm if the modifications are OK ?

https://gitlab.com/JackoboLeChocobo/WineScripts/blob/master/wine-staging-3.2/patches-after-staging-app/after-staging-app-d3d9.patch

**Comment by GloriousEggroll** [comment]
@JackoboLeChocobo url gives 404 error

**Comment by GloriousEggroll** [comment]
fixed 6fa35e72e243cb74ef6bd1739fd1101a026cefb2

**Pull request closed without merging**
