### PR TITLE
rebase against 7deb0909a9ace8802d2729fc17d74849ea3f4ff3

### PR DESCRIPTION
**Pull request by stefson**
This is not a complete rebase, it is just that I don't really feel comfortable with rebasing 'wined3d-Viewports' on my own - you can merge this or include it in a bigger and more complete fix.

### CODE REVIEW

**Comment by stefson** [comment]
Ok, so with 544a7daaebcdd329517854b32c4f8f42374cde4f the get_viewport() function was factored out, which is the reason for the failure of 'wined3d-Viewports' ; essentially the part about dlls/wined3d/state.c

As I said, too difficult for me :)

**Comment by stefson** [comment]
With current head of git, which patches are failing as well for you? Those I removed here were merged 1:1 and therefore can be removed without having deeper knowledge of the code, which I lack of ;-)

**Comment by alesliehughes** [comment]
I have done the rebase already but have to do some testing before pushing.

**Comment by alesliehughes** [comment]
Rebased.

**Pull request closed without merging**
